Log:
  Level: debug                    # 日志级别: none, error, warning, info, debug
  AccessPath:                     # 访问日志路径: /etc/XrayR/access.log
  ErrorPath:                      # 错误日志路径: /etc/XrayR/error.log
DnsConfigPath:                    # DNS 配置文件路径: /etc/XrayR/dns.json，参考 https://xtls.github.io/config/dns.html
RouteConfigPath:                  # 路由配置文件路径: /etc/XrayR/route.json，参考 https://xtls.github.io/config/routing.html
InboundConfigPath:                # 自定义入站配置路径: /etc/XrayR/custom_inbound.json，参考 https://xtls.github.io/config/inbound.html
OutboundConfigPath:               # 自定义出站配置路径: /etc/XrayR/custom_outbound.json，参考 https://xtls.github.io/config/outbound.html
ConnectionConfig:
  Handshake: 4                    # 握手时间限制，单位：秒
  ConnIdle: 30                    # 连接空闲时间限制，单位：秒
  UplinkOnly: 2                   # 下行关闭后的时间限制，单位：秒
  DownlinkOnly: 4                 # 上行关闭后的时间限制，单位：秒
  BufferSize: 64                  # 每个连接的内部缓存大小，单位：kB
Nodes:
  -
    PanelType: NewV2board         # 面板类型: SSpanel, V2board, NewV2board, PMpanel, Proxypanel, V2RaySocks
    ApiConfig:
      ApiHost: ${APIHOST}
      ApiKey: ${APIKEY}
      NodeID: ${NODEID}
      NodeType: Shadowsocks       # 节点类型: V2ray, Vmess, Vless, Shadowsocks, Trojan, Shadowsocks-Plugin
      Timeout: 30                 # API 请求超时时间，单位：秒
      EnableVless: false          # 为 V2ray 类型启用 Vless
      EnableXTLS: false           # 为 V2ray 和 Trojan 启用 XTLS
      SpeedLimit: 0               # 本地限速设置，单位：Mbps，0 表示禁用
      DeviceLimit: 0              # 本地设备数限制，0 表示禁用
      RuleListPath:               # 本地规则列表文件路径: /etc/XrayR/rulelist
    ControllerConfig:
      ListenIP: 0.0.0.0           # 监听的 IP 地址
      SendIP: 0.0.0.0             # 发送数据包的 IP 地址
      UpdatePeriodic: 60          # 更新节点信息的时间间隔，单位：秒
      EnableDNS: false            # 使用自定义 DNS 配置，请确保正确设置 dns.json
      DNSType: AsIs               # DNS 策略: AsIs, UseIP, UseIPv4, UseIPv6
      EnableProxyProtocol: false  # 启用 PROXY 协议，仅适用于 WebSocket 和 TCP
      AutoSpeedLimitConfig:
        Limit: 0                  # 警告速度，单位：mbps，设置为 0 禁用自动限速
        WarnTimes: 0              # 连续警告次数后限速，设置为 0 立即惩罚超速用户
        LimitSpeed: 0             # 限速用户的速度限制，单位：mbps
        LimitDuration: 0          # 限速持续时间，单位：分钟
      GlobalDeviceLimitConfig:
        Enable: false             # 启用全局设备数限制
        RedisAddr: 127.0.0.1:6379 # Redis 服务器地址
        RedisPassword: YOUR PASSWORD # Redis 密码
        RedisDB: 0                # Redis 数据库编号
        Timeout: 5                # Redis 请求超时时间，单位：秒
        Expiry: 60                # 过期时间，单位：秒
      EnableFallback: false       # 启用回落功能，仅支持 Trojan 和 Vless
      FallBackConfigs:            # 支持多个回落配置
        -
          SNI:                    # TLS SNI（服务器名称指示），留空表示任意
          Alpn:                   # Alpn 协议，留空表示任意
          Path:                   # HTTP 路径，留空表示任意
          Dest: 80                # 必填，回落目标地址，详见 https://xtls.github.io/config/features/fallback.html
          ProxyProtocolVer: 0     # 发送 PROXY 协议版本，0 表示禁用
      CertConfig:
        CertMode: dns             # 证书获取方式: none, file, http, tls, dns。选择 "none" 将强制禁用 TLS 配置
        CertDomain: "node1.test.com" # 证书域名
        CertFile: /etc/XrayR/cert/node1.test.com.cert # 证书文件路径（CertMode 为 file 时提供）
        KeyFile: /etc/XrayR/cert/node1.test.com.key   # 密钥文件路径
        Provider: alidns          # DNS 证书提供商，完整列表见 https://go-acme.github.io/lego/dns/
        Email: test@me.com        # 邮箱地址
        DNSEnv:                   # DNS 提供商使用的环境变量
          ALICLOUD_ACCESS_KEY: aaa
          ALICLOUD_SECRET_KEY: bbb